name: Build and Deploy Zomato Clone

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # Step 1: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 2: Deploy to host machine
      - name: Deploy to host machine
        run: |
          ssh -o StrictHostKeyChecking=no icanio-10163@192.168.29.8 << 'EOF'
            # Stop and remove any existing container
            docker stop zomatodemo || true
            docker rm zomatodemo || true

            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo:latest

            # Run the new container
            docker run -d --name zomatodemo -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo:latest
          EOF
