name: Build and Deploy Zomato Clone Locally

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo:latest ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo:$(date +"%Y%m%d-%H%M%S")
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo:$(date +"%Y%m%d-%H%M%S")

      # Step 5: Stop and backup the existing container
      - name: Stop and backup existing container
        run: |
          docker rename zomatodemo zomatodemo_backup || true
          docker stop zomatodemo_backup || true

      # Step 6: Run the new container
      - name: Run new Docker container
        run: |
          docker run -d --name zomatodemo -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/zomatodemo:latest || {
            echo "Deployment failed, rolling back...";
            docker start zomatodemo_backup;
            exit 1;
          }

      # Step 7: Cleanup backup container if deployment succeeds
      - name: Cleanup backup container
        run: |
          docker rm zomatodemo_backup || true
